Add nginx image
unit9/docklabs pull request #26
Opened 2017-02-23 14:39 UTC by esenti

Simple image containing ngnix for serving static content.

2017-02-23 14:43 UTC, rollcat commented
Why not https://github.com/unit9/docklabs/tree/master/kubenginx ?

2017-02-23 14:52 UTC, esenti commented
I think it's a good idea to have a simple nginx image where you can just `COPY` your static content and have it served, without need for further configuration and with no k8s-specific parts. Though `kubenginx` would probably work too.

2017-02-23 14:58 UTC, rollcat commented
You can do all of that with `kubenginx` too. It has some hooks to play nice with k8s, but I don't think there's anything that would stop you from using it anywhere else.

If we'd like a separate / simpler image, I'd say we should have a base nginx + customisations for specific things (like k8s).

2017-02-23 15:21 UTC, esenti commented
We already have another nginx image, with PHP support: https://github.com/unit9/docklabs/tree/master/nginx-php5. But yes, it might be a good idea to create a common image and customize it for k8s/PHP.

2017-02-23 16:52 UTC, esenti commented
Made both `nginx-php5` and `kubenginx` use use the base `nginx` image and add custom config to it.

2017-02-23 17:01 UTC, rollcat approved these changes
Cool! Can you please adjust the image build dependencies in all automated builds on Dockerhub before you merge?

2017-02-23 17:02 UTC, rollcat commented on kubenginx/Dockerfile
>  ADD rc.local   /etc/rc.local
Overrides nginx.rc from base nginx?

2017-02-23 17:02 UTC, rollcat commented on kubenginx/Dockerfile
>  ADD nginx.run  /etc/service/nginx/run
Overrides nginx.rc from base nginx?

2017-02-23 17:04 UTC, rollcat commented on nginx-php5/Dockerfile
Line 14 (sorry github doesn't allow me to post a comment there), it looks like the nginx.conf is installed as the default site, and nginx.conf from base nginx doesn't pull it

2017-02-23 17:04 UTC, rollcat requested changes
Sorry, thought it was ok, found some issues

2017-02-23 17:17 UTC, esenti commented on kubenginx/Dockerfile
>  ADD nginx.run  /etc/service/nginx/run
Right, no need to do this.

2017-02-23 17:18 UTC, esenti commented on nginx-php5/Dockerfile
The default nginx config (that the base uses) will pull it.

2017-02-23 17:25 UTC, rollcat commented on nginx-php5/Dockerfile
Wait, I see the problem.

Everything is named nginx.conf, but ends up in various places that are not /etc/nginx/nginx.conf. Not good.

Some things are named nginx.run, or nginx.rc, or else, but they all end up in /etc/service/nginx/run. Not good.

Some things override other random things.

Let me fix ;)

2017-02-23 17:30 UTC, rollcat commented on nginx-php5/Dockerfile
https://github.com/unit9/docklabs/commits/feature/nginx-proposed ?

2017-02-24 12:26 UTC, esenti commented on nginx-php5/Dockerfile
Looks good, pulled the commits into this PR.

2017-02-24 13:44 UTC, rollcat approved these changes

2017-02-24 13:47 UTC, merged