Webstack with node 7 image
unit9/docklabs pull request #8
Opened 2017-01-04 16:15 UTC by tjomk

- Install gcloud
- Add new image with node 7

2017-01-04 16:40 UTC, rollcat requested changes

2017-01-04 16:40 UTC, rollcat commented on python-uwsgi/Dockerfile
> +RUN export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)" \
Why would you *need* this here? You're bloating a single-purposed base image, that doesn't need this 99.9% of the time

2017-01-04 16:40 UTC, rollcat commented on python-uwsgi/Dockerfile
> +FROM unit9/base:latest
Please don't change capitalisation, stick to the current convention (whatever the convention is)

2017-01-04 16:40 UTC, rollcat commented on webstack-node7/Dockerfile
> +from unit9/python-uwsgi:latest
Again, inconsistent capitalisation

2017-01-04 16:40 UTC, rollcat commented on webstack-node7/readme.md
> +See [the readme for `unit9/webstack`](/webstack).
Not based on unit9/webstack?

2017-01-05 08:56 UTC, tjomk commented on webstack-node7/readme.md
> +See [the readme for `unit9/webstack`](/webstack).
Nope, it installs node 4

2017-01-05 08:57 UTC, tjomk commented on shippable/Dockerfile
> +FROM unit9/base:latest
Need this image for building on Shippable. The base image they provide has old Node, and for pushing builds to repo we need awscli/gcloud.

2017-01-05 09:35 UTC, rollcat commented on webstack-node7/readme.md
> +See [the readme for `unit9/webstack`](/webstack).
Ah yeah, readme from webstack still mostly applies

2017-01-05 10:42 UTC, rollcat requested changes

2017-01-05 10:42 UTC, rollcat commented on shippable/Makefile
> +TAG = unit9/python-uwsgi
wrong tag!

2017-01-05 10:56 UTC, rollcat approved these changes

2017-01-05 10:57 UTC, merged